thehyve/podium

- podium-gateway/src/main/webapp/app/account/register/register.component.html
- podium-gateway/src/main/webapp/app/shared/specialism/specialism.component.html
- podium-gateway/src/main/webapp/i18n/en/global.json
- podium-gateway/src/test/javascript/spec/app/shared/specialism/specialism.component.spec.ts
- validate max 50 char for firstname & lastname
- validate max 150 char for some fields (dept, institution, function)
- added telephone validation
- placeholder text for other specialism
> Fix issues registration form

- podium-gateway/src/main/webapp/app/account/register/register.component.html
- podium-gateway/src/main/webapp/app/account/register/register.component.ts
- podium-gateway/src/main/webapp/app/shared/index.ts
- podium-gateway/src/main/webapp/app/shared/shared.module.ts
- podium-gateway/src/main/webapp/app/shared/validators/password-validator.directive.ts
- podium-gateway/src/test/javascript/spec/app/shared/validators/password-validator.directive.spec.ts
Add password validation to have minimum 8 chars contains alphanumeric and non-alphanumeric
> Password validation

- podium-common/src/main/java/nl/thehyve/podium/common/request/DecisionOutcome.java
- podium-common/src/main/java/nl/thehyve/podium/common/request/RequestReviewStatus.java
- podium-gateway/pom.xml
- podium-gateway/src/main/java/nl/thehyve/podium/PodiumGatewayApp.java
- podium-gateway/src/main/java/nl/thehyve/podium/config/ProcessEngineConfiguration.java
- podium-gateway/src/main/java/nl/thehyve/podium/domain/Request.java
- podium-gateway/src/main/java/nl/thehyve/podium/domain/RequestReviewProcess.java
- podium-gateway/src/main/java/nl/thehyve/podium/exceptions/ActionNotAllowedInStatus.java
- podium-gateway/src/main/java/nl/thehyve/podium/exceptions/ResourceNotFound.java
- podium-gateway/src/main/java/nl/thehyve/podium/repository/RequestReviewProcessRepository.java
- podium-gateway/src/main/java/nl/thehyve/podium/repository/search/RequestReviewProcessSearchRepository.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/RequestReviewProcessService.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/RequestService.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/mapper/PrincipalInvestigatorMapper.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/mapper/RequestMapper.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/representation/PrincipalInvestigatorRepresentation.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/representation/RequestRepresentation.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/representation/RequestReviewRepresentation.java
- podium-gateway/src/main/java/nl/thehyve/podium/web/rest/RequestResource.java
- podium-gateway/src/main/resources/config/liquibase/act_ge_property.csv
- podium-gateway/src/main/resources/config/liquibase/act_id_property.csv
- podium-gateway/src/main/resources/config/liquibase/changelog/20170314124429_add_request_review_process.xml
- podium-gateway/src/main/resources/config/liquibase/changelog/20170314143552_added_flowable.xml
- podium-gateway/src/main/resources/config/liquibase/master.xml
- podium-gateway/src/main/resources/processes/podium_request_review.001.bpmn20.xml
- podium-gateway/src/test/java/nl/thehyve/podium/service/RequestReviewProcessServiceIntTest.java
- podium-gateway/src/test/java/nl/thehyve/podium/web/rest/RequestResourceIntTest.java
- pom.xml
- Added `flowable` dependency;
- BPMN definition for the reviewing process;
- `RequestReviewProcess` entity (and database table);
- A service for starting reviewing process instances and completing tasks, moving to the next status.
Completes [PODIUM-58](https://jira.thehyve.nl/browse/PODIUM-58) (process) and [PODIUM-60](https://jira.thehyve.nl/browse/PODIUM-60) (BPMN framework).
> Request review process definition and service.

- podium-gateway/src/main/resources/processes/podium_request_review.001.bpmn20.xml
- podium-gateway/src/main/webapp/app/account/password-reset/finish/password-reset-finish.component.html
- podium-gateway/src/main/webapp/app/account/password-reset/finish/password-reset-finish.component.ts
- podium-gateway/src/main/webapp/app/account/register/register.component.html
- podium-gateway/src/main/webapp/app/account/register/register.component.ts
- podium-gateway/src/main/webapp/app/entities/user-management/user-management-dialog.component.html
- podium-gateway/src/main/webapp/app/shared/index.ts
- podium-gateway/src/main/webapp/app/shared/shared.module.ts
- podium-gateway/src/main/webapp/app/shared/validators/password-matches.directive.ts
- podium-gateway/src/main/webapp/i18n/en/global.json
- podium-gateway/src/test/javascript/spec/app/account/register/register.component.spec.ts
- podium-gateway/src/test/javascript/spec/app/shared/validators/password-matches.directive.spec.ts
- podium-uaa/src/main/java/nl/thehyve/podium/security/CustomServerAuthenticationProvider.java
- podium-uaa/src/main/java/nl/thehyve/podium/service/UserService.java
- podium-uaa/src/main/java/nl/thehyve/podium/service/representation/UserRepresentation.java
- podium-uaa/src/main/java/nl/thehyve/podium/web/rest/AccountResource.java
- podium-uaa/src/main/java/nl/thehyve/podium/web/rest/UserResource.java
- podium-uaa/src/test/java/nl/thehyve/podium/web/rest/AccountResourceIntTest.java
- podium-uaa/src/test/java/nl/thehyve/podium/web/rest/RoleResourceIntTest.java
- podium-uaa/src/test/java/nl/thehyve/podium/web/rest/UserResourceIntTest.java
Fixes [PODIUM-8](https://jira.thehyve.nl/browse/PODIUM-8).
> Registration backend validation

- podium-common/src/main/java/nl/thehyve/podium/common/service/dto/OrganisationDTO.java
- podium-gateway/src/main/resources/processes/podium_request_review.001.bpmn20.xml
- podium-gateway/src/main/webapp/app/account/password-reset/finish/password-reset-finish.component.html
- podium-gateway/src/main/webapp/app/account/password-reset/finish/password-reset-finish.component.ts
- podium-gateway/src/main/webapp/app/account/register/register.component.html
- podium-gateway/src/main/webapp/app/account/register/register.component.ts
- podium-gateway/src/main/webapp/app/entities/user-management/user-management-dialog.component.html
- podium-gateway/src/main/webapp/app/shared/index.ts
- podium-gateway/src/main/webapp/app/shared/shared.module.ts
- podium-gateway/src/main/webapp/app/shared/validators/password-matches.directive.ts
- podium-gateway/src/main/webapp/i18n/en/global.json
- podium-gateway/src/test/javascript/spec/app/account/register/register.component.spec.ts
- podium-gateway/src/test/javascript/spec/app/shared/validators/password-matches.directive.spec.ts
- podium-uaa/src/main/java/nl/thehyve/podium/security/CustomServerAuthenticationProvider.java
- podium-uaa/src/main/java/nl/thehyve/podium/service/TestService.java
- podium-uaa/src/main/java/nl/thehyve/podium/service/UserService.java
- podium-uaa/src/main/java/nl/thehyve/podium/service/representation/UserRepresentation.java
- podium-uaa/src/main/java/nl/thehyve/podium/web/rest/AccountResource.java
- podium-uaa/src/main/java/nl/thehyve/podium/web/rest/OrganisationResource.java
- podium-uaa/src/main/java/nl/thehyve/podium/web/rest/TestResource.java
- podium-uaa/src/main/java/nl/thehyve/podium/web/rest/UserResource.java
- podium-uaa/src/main/resources/config/liquibase/changelog/20170404150743_remove_user_authorities.xml
- podium-uaa/src/main/resources/config/liquibase/master.xml
- podium-uaa/src/test/java/nl/thehyve/podium/web/rest/AccountResourceIntTest.java
- podium-uaa/src/test/java/nl/thehyve/podium/web/rest/RoleResourceIntTest.java
- podium-uaa/src/test/java/nl/thehyve/podium/web/rest/TestResourceIntTest.java
- podium-uaa/src/test/java/nl/thehyve/podium/web/rest/UserResourceIntTest.java
Includes changes from #50.
Fixes [PODIUM-70](https://jira.thehyve.nl/browse/PODIUM-70).
> Backend test routes

- podium-gateway/src/main/webapp/app/shared/role/role-assign/role-assign.component.html
- podium-gateway/src/main/webapp/content/scss/global.scss
- podium-uaa/src/main/java/nl/thehyve/podium/service/decorators/UserMapperDecorator.java
- [Podium-56](https://jira.thehyve.nl/browse/PODIUM-56)
> Role assign fixes

- podium-gateway/src/main/java/nl/thehyve/podium/service/mapper/RequestMapper.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/mapper/RequestReviewProcessMapper.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/representation/RequestRepresentation.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/representation/RequestReviewRepresentation.java
- podium-gateway/src/main/webapp/app/request/main-detail/progress-bar/request-progress-bar.component.html
- podium-gateway/src/main/webapp/app/request/main-detail/progress-bar/request-progress-bar.component.ts
- podium-gateway/src/main/webapp/app/request/request.route.ts
- podium-gateway/src/main/webapp/app/shared/request/action-bars/request-action-toolbar/request-action-toolbar.component.html
- podium-gateway/src/main/webapp/app/shared/request/action-bars/request-action-toolbar/request-action-toolbar.component.ts
- podium-gateway/src/main/webapp/app/shared/request/request-base.ts
- podium-gateway/src/main/webapp/app/shared/request/request-review-decision.ts
- podium-gateway/src/main/webapp/app/shared/request/request-review.ts
- podium-gateway/src/main/webapp/app/shared/request/request-status/request-status.constants.ts
- podium-gateway/src/main/webapp/i18n/en/requestStatus.json
RequestReviewMapper
UI logic for progress bar
> Review status indication

- podium-gateway/src/main/resources/config/application.yml
- podium-uaa/src/main/resources/config/application.yml
Disabled hazelcast phone home 'feature'
> Disable hazelcast phone home

- podium-gateway/src/main/webapp/app/admin/gateway/gateway.component.html
- podium-gateway/src/main/webapp/app/admin/health/health.component.html
- podium-gateway/src/main/webapp/app/admin/metrics/metrics.component.html
- podium-gateway/src/main/webapp/app/backoffice/modules/organisation/organisation-delete-dialog.component.html
- podium-gateway/src/main/webapp/app/backoffice/modules/organisation/organisation-detail.component.html
- podium-gateway/src/main/webapp/app/backoffice/modules/organisation/organisation-dialog.component.html
- podium-gateway/src/main/webapp/app/backoffice/modules/organisation/organisation-form/organisation-form.component.html
- podium-gateway/src/main/webapp/app/backoffice/modules/organisation/organisation.component.html
- podium-gateway/src/main/webapp/app/backoffice/modules/user-management/user-management-delete-dialog.component.html
- podium-gateway/src/main/webapp/app/backoffice/modules/user-management/user-management-detail.component.html
- podium-gateway/src/main/webapp/app/backoffice/modules/user-management/user-management-dialog.component.html
- podium-gateway/src/main/webapp/app/backoffice/modules/user-management/user-management-unlock-dialog.component.html
- podium-gateway/src/main/webapp/app/backoffice/modules/user-management/user-management.component.html
- podium-gateway/src/main/webapp/app/request/form/request-form-submit-dialog.component.html
- podium-gateway/src/main/webapp/app/request/overview/request-overview.component.html
- podium-gateway/src/main/webapp/app/shared/upload/upload-dialog.component.html
- podium-gateway/webpack/webpack.prod.js
- Remove link in organisation overview
- Fix webpack production environment
- Update all icons from font-awesome to material design
> Remove link organisation overview

- podium-common/src/main/java/nl/thehyve/podium/common/resource/InternalUserResource.java
- podium-gateway/src/main/java/nl/thehyve/podium/client/InternalUserClient.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/MailService.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/NotificationService.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/RequestService.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/UserClientService.java
- podium-gateway/src/main/resources/i18n/messages.properties
- podium-gateway/src/main/resources/i18n/messages_en.properties
- podium-gateway/src/main/resources/mails/organisationRequestSubmitted.html
- podium-gateway/src/main/resources/mails/requesterRequestSubmitted.html
- podium-gateway/src/test/java/nl/thehyve/podium/service/UserClientServiceIntTest.java
- podium-gateway/src/test/java/nl/thehyve/podium/web/rest/RequestResourceIntTest.java
- podium-uaa/src/main/java/nl/thehyve/podium/web/rest/InternalUserServer.java
Send notification mail to requester when submitting a request.
Fixes [PODIUM-81](https://jira.thehyve.nl/browse/PODIUM-81).
> Requester submission notification email.

- podium-gateway/src/main/webapp/app/request/form/request-form.component.html
- podium-gateway/src/main/webapp/app/request/form/request-form.component.ts
- podium-gateway/src/main/webapp/app/shared/organisation-selector/organisation-selector.component.ts
- podium-gateway/src/main/webapp/i18n/en/request.json
- podium-gateway/src/test/javascript/spec/app/shared/organisation-selector/organisation-selector.component.spec.ts
- Clear organisation selector when request type changed
- Reorganize form fields to have request details on the top
> Clear organisation selector

- podium-gateway/src/main/java/nl/thehyve/podium/repository/RequestRepository.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/RequestService.java
- podium-gateway/src/main/java/nl/thehyve/podium/web/rest/RequestResource.java
- podium-gateway/src/main/resources/config/application.yml
- podium-gateway/src/main/webapp/app/request/overview/request-overview.component.ts
- podium-gateway/src/main/webapp/app/shared/request/request.service.ts
- podium-gateway/src/test/java/nl/thehyve/podium/web/rest/RequestResourceIntTest.java
- podium-gateway/src/test/javascript/spec/app/shared/request/request.service.spec.ts
- podium-gateway/src/test/resources/config/application.yml
- podium-uaa/src/main/resources/config/application.yml
- podium-uaa/src/test/resources/config/application.yml
- Provide different route for organisational request overview
- Initialize unit testing for request-overview
> Add new route for organisational request overview

- podium-common/src/main/java/nl/thehyve/podium/common/event/StatusUpdateEvent.java
- podium-gateway/src/main/java/nl/thehyve/podium/event/StatusUpdateEventListener.java
- podium-gateway/src/main/java/nl/thehyve/podium/repository/RequestRepository.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/MailService.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/NotificationService.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/RequestService.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/TestService.java
- podium-gateway/src/main/java/nl/thehyve/podium/web/rest/RequestResource.java
- podium-gateway/src/main/resources/logback-spring.xml
- podium-gateway/src/main/webapp/app/request/main-detail/detail/request-detail.component.ts
- podium-gateway/src/main/webapp/app/request/overview/request-overview.component.ts
- podium-gateway/src/main/webapp/app/shared/request/request.service.ts
- podium-gateway/src/test/java/nl/thehyve/podium/web/rest/RequestResourceIntTest.java
- podium-gateway/src/test/javascript/spec/app/shared/request/request.service.spec.ts
- podium-gateway/src/test/resources/config/application.yml
- podium-gateway/src/test/resources/logback-test.xml
- podium-uaa/src/test/resources/logback-test.xml
- travis/scripts/02-tests.sh
- New route for fetching reviewer requests
- Refactor of RequestService (homogenised the access and status checks, notifications in event listener)
- Refactor of RequestResource
- Refactor of RequestReourceIntTest: tests not transactional anymore (to enable notification functionality)
> Fetching requests for reviewers; Refactored request resource.

- podium-common/src/main/java/nl/thehyve/podium/common/resource/InternalRequestResource.java
- podium-common/src/main/java/nl/thehyve/podium/common/service/RequestSecurityService.java
- podium-common/src/main/java/nl/thehyve/podium/common/service/dto/RequestRepresentation.java
- podium-gateway/src/main/java/nl/thehyve/podium/internal/InternalRequestServer.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/NotificationService.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/RequestService.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/mapper/RequestMapper.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/util/DefaultUser.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/util/ExtendedUser.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/util/UserMapperHelper.java
- podium-gateway/src/main/webapp/app/backoffice/modules/organisation/organisation.component.html
- podium-gateway/src/main/webapp/app/backoffice/modules/user-management/user-management.component.html
- podium-gateway/src/main/webapp/app/request/main-detail/request-main-detail.component.html
- podium-gateway/src/main/webapp/app/request/overview/request-overview.component.html
- podium-gateway/src/main/webapp/app/request/overview/request-overview.component.ts
- podium-gateway/src/main/webapp/app/request/overview/request-overview.route.ts
- podium-gateway/src/main/webapp/app/request/request.module.ts
- podium-gateway/src/main/webapp/app/shared/event/podium-event-message.component.html
- podium-gateway/src/main/webapp/app/shared/event/podium-event-message.component.scss
- podium-gateway/src/main/webapp/app/shared/event/podium-event-message.component.ts
- podium-gateway/src/main/webapp/app/shared/request/request-access.service.ts
- podium-gateway/src/main/webapp/app/shared/request/request-base.ts
- podium-gateway/src/main/webapp/app/shared/shared.module.ts
- podium-gateway/src/main/webapp/app/shared/status-update/request-status-update.component.html
- podium-gateway/src/main/webapp/i18n/en/request.json
- podium-gateway/src/test/java/nl/thehyve/podium/web/rest/AccessPolicyIntTest.java
- podium-uaa/src/main/java/nl/thehyve/podium/service/decorators/UserMapperDecorator.java
Usermapper helper for mapping requesters in Requests.
UI component to display most recent message for coordinator feedback
> Status updates

- podium-gateway/src/test/javascript/e2e/data/data-dictionary.ts
- podium-gateway/src/test/javascript/e2e/data/example.txt
- podium-gateway/src/test/javascript/e2e/data/templates.ts
- podium-gateway/src/test/javascript/e2e/protractor-stories/director.ts
- added a function to upload files
> E2e file upload

- podium-gateway/package.json
- podium-gateway/src/test/javascript/e2e/protractor-stories/admin-console.ts
- podium-gateway/src/test/javascript/e2e/stepdefinitions/bbmri-admin-organistations.ts
- podium-gateway/src/test/javascript/e2e/stepdefinitions/requests.ts
- added package request-promise-native
- functions that do http calls no longer need a callback parameter to be called when they are done.
> refactor admin-console to only use promise based requests

- .travis.yml
- podium-gateway/src/test/javascript/e2e/stepdefinitions/hooks.ts
- podium-uaa/src/main/java/nl/thehyve/podium/service/UserService.java
- podium-uaa/src/test/java/nl/thehyve/podium/web/rest/AccessPolicyIntTest.java
- travis/scripts/03-run.sh
- split e2e tests into separate jobs for different browsers
- tweaking the timing of the tests.
> Travis e2e jobs timing

- podium-common/src/main/java/nl/thehyve/podium/common/aop/security/AccessPolicyAspect.java
- podium-common/src/main/java/nl/thehyve/podium/common/test/AbstractAuthorisedUserIntTest.java
- podium-gateway/src/main/webapp/app/backoffice/modules/organisation/organisation.component.ts
- podium-gateway/src/main/webapp/app/backoffice/modules/organisation/organisation.service.ts
- podium-gateway/src/test/java/nl/thehyve/podium/web/rest/AccessPolicyIntTest.java
- podium-gateway/src/test/javascript/e2e/features/login-account.feature
- podium-gateway/src/test/javascript/e2e/protractor-stories/admin-console.ts
- podium-gateway/src/test/javascript/e2e/stepdefinitions/hooks.ts
- podium-uaa/src/main/java/nl/thehyve/podium/repository/OrganisationRepository.java
- podium-uaa/src/main/java/nl/thehyve/podium/repository/UserRepository.java
- podium-uaa/src/main/java/nl/thehyve/podium/security/CustomServerAuthenticationProvider.java
- podium-uaa/src/main/java/nl/thehyve/podium/service/OrganisationService.java
- podium-uaa/src/main/java/nl/thehyve/podium/service/TestService.java
- podium-uaa/src/main/java/nl/thehyve/podium/service/UserService.java
- podium-uaa/src/main/java/nl/thehyve/podium/web/rest/OrganisationServer.java
- podium-uaa/src/main/java/nl/thehyve/podium/web/rest/TestResource.java
- podium-uaa/src/test/java/nl/thehyve/podium/web/rest/AccessPolicyIntTest.java
- podium-uaa/src/test/java/nl/thehyve/podium/web/rest/OrganisationResourceIntTest.java
- podium-uaa/src/test/java/nl/thehyve/podium/web/rest/TestResourceIntTest.java
Added `/organisations/admin` for organisation admins. Fetches the organisations for which they are coordinator.
> Admin organisations route

- podium-gateway/package.json
- podium-gateway/src/main/webapp/app/request/main-detail/request-finalize-dialog/request-finalize-dialog.component.ts
- podium-gateway/src/main/webapp/app/request/request.module.ts
- podium-gateway/src/main/webapp/app/shared/request/request.service.ts
- Update UI version to 0.0.2
- Pagination fix importing NgbModule
- Rename finalizeRequest to closeRequest in RequestService
> Minor fixes pagination versioning

- podium-gateway/src/main/java/nl/thehyve/podium/service/MailService.java
- podium-gateway/src/main/resources/mails/organisationDeliveryReceived.html
- podium-gateway/src/main/resources/mails/requesterDeliveryCancelled.html
- podium-gateway/src/main/resources/mails/requesterDeliveryReleased.html
- Fix subjects in delivery emails;
- Fix link in delivery emails: refers to request details page now.
> Fix delivery email subjects.

- podium-gateway/src/main/webapp/app/request/main-detail/detail/request-detail.component.html
- podium-gateway/src/main/webapp/app/request/main-detail/detail/request-detail.component.ts
- podium-gateway/src/main/webapp/app/request/main-detail/progress-bar/request-progress-bar.component.html
- podium-gateway/src/main/webapp/app/request/main-detail/progress-bar/request-progress-bar.component.ts
- podium-gateway/src/main/webapp/app/request/main-detail/progress-bar/request-progress-bar.scss
- podium-gateway/src/main/webapp/app/request/overview/request-overview.component.html
- podium-gateway/src/main/webapp/app/request/overview/request-overview.component.ts
- podium-gateway/src/main/webapp/app/request/request-delivery-panel/request-delivery-panel.component.ts
- podium-gateway/src/main/webapp/app/shared/delivery-update/delivery-update.component.ts
- podium-gateway/src/main/webapp/app/shared/request/action-bars/request-action-toolbar/request-action-toolbar.component.html
- podium-gateway/src/main/webapp/app/shared/request/action-bars/request-action-toolbar/request-action-toolbar.component.ts
- podium-gateway/src/main/webapp/app/shared/request/request-outcome.ts
- podium-gateway/src/main/webapp/app/shared/request/request.service.ts
- podium-gateway/src/main/webapp/app/shared/status-update/request-update-dialog.component.ts
- podium-gateway/src/main/webapp/app/shared/status-update/request-update-dialog.scss
- podium-gateway/src/main/webapp/app/shared/status-update/request-update-status-dialog.component.ts
- podium-gateway/src/main/webapp/i18n/en/request.json
- podium-gateway/src/main/webapp/i18n/en/requestOutcome.json
- podium-gateway/src/test/javascript/spec/app/request/main-detail/progress-bar/request-progress-bar.component.spec.ts
- podium-uaa/src/main/java/nl/thehyve/podium/service/UserService.java
- Add close request functionality while in Approved status
- Progress bar support for new Closed state and request outcome
- Request overview approved button
- Update deliveries after closing status update panel
- Also update search user when using generic save wrapper in UserService
> Various fixes from tests

- podium-gateway/src/main/webapp/app/request/main-detail/detail/request-detail.component.ts
This is a fix for [PODIUM-166](https://jira.thehyve.nl/browse/PODIUM-166)
> update on currentUser triggers check for isInRevision

- podium-gateway/src/main/webapp/app/request/form/request-form.component.html
- podium-gateway/src/main/webapp/i18n/en/request.json
Refactor checkbox to radio button
> Change isLinked request checkbox to radio button.

- podium-gateway/src/main/java/nl/thehyve/podium/service/DraftService.java
- podium-gateway/src/main/webapp/app/request/form/request-form.component.html
- podium-gateway/src/main/webapp/app/request/form/request-form.component.ts
- podium-gateway/src/main/webapp/app/request/main-detail/request-main-detail.component.html
- enable radio button when user selects > 1 organisations
- set default value linked request to false
> Linked request

- podium-gateway/src/main/webapp/app/account/register/register.component.ts
- podium-gateway/src/main/webapp/app/layouts/completed/completed.component.html
- podium-gateway/src/main/webapp/app/layouts/completed/completed.component.ts
- podium-gateway/src/main/webapp/app/layouts/completed/completed.scss
- podium-gateway/src/main/webapp/app/layouts/completed/completion-type.ts
- podium-gateway/src/main/webapp/app/layouts/main/main.component.ts
- podium-gateway/src/main/webapp/app/layouts/navbar/navbar.component.html
- podium-gateway/src/main/webapp/app/layouts/navbar/navbar.component.ts
- podium-gateway/src/main/webapp/app/layouts/navbar/navbar.scss
- podium-gateway/src/main/webapp/app/request/form/request-form-submit-dialog.component.ts
- podium-gateway/src/main/webapp/app/request/overview/request-overview.component.html
- podium-gateway/src/main/webapp/app/shared/message/message.model.ts
- podium-gateway/src/main/webapp/i18n/en/register.json
- Fixes PODIUM-179
- Various fixes in navbar and overview screens
> Registration redirect

- podium-gateway/src/main/webapp/app/backoffice/modules/organisation/organisation.component.html
- podium-gateway/src/main/webapp/app/backoffice/modules/user-management/user-management-delete-dialog.component.html
- podium-gateway/src/main/webapp/app/backoffice/modules/user-management/user-management-dialog.component.html
- podium-gateway/src/main/webapp/app/backoffice/modules/user-management/user-management.component.html
- podium-gateway/src/test/javascript/e2e/features/bbmri-admin-organisations.feature
- podium-gateway/src/test/javascript/e2e/features/bbmri-admin-users-overview.feature
- podium-gateway/src/test/javascript/e2e/features/login-account.feature
- podium-gateway/src/test/javascript/e2e/pages/modules/organisations-details.ts
- podium-gateway/src/test/javascript/e2e/pages/organisations-details.page.ts
- podium-gateway/src/test/javascript/e2e/pages/user-details.page.ts
- podium-gateway/src/test/javascript/e2e/protractor-stories/admin-console.ts
- podium-gateway/src/test/javascript/e2e/protractor-stories/director.ts
- podium-gateway/src/test/javascript/e2e/stepdefinitions/bbmri-admin-organistations.ts
- podium-gateway/src/test/javascript/e2e/stepdefinitions/bbmri-admin-users-overview.ts
- podium-gateway/src/test/javascript/e2e/stepdefinitions/login-accounts.ts
- podium-gateway/src/test/javascript/e2e/stepdefinitions/org-admin-edit.ts
- podium-gateway/src/test/javascript/e2e/stepdefinitions/util.ts
fixed cases for the bbmri admin user.
including [PODIUM-200](https://jira.thehyve.nl/browse/PODIUM-200)
> bbmri-admin cases

- podium-gateway/src/main/webapp/app/app.route.ts
- podium-gateway/src/main/webapp/app/home/home.component.html
- podium-gateway/src/main/webapp/app/home/home.component.ts
- podium-gateway/src/main/webapp/app/layouts/navbar/navbar.component.html
- podium-gateway/src/main/webapp/app/shared/login/login.component.ts
- podium-gateway/src/main/webapp/app/shared/login/login.service.ts
- Redirect users based on roles
- Remove dashboard links
> Role base redirection

- README.md
- podium-gateway/README.md
- podium-gateway/src/test/javascript/e2e/features/login-account.feature
- podium-gateway/src/test/javascript/e2e/pages/user-management.page.ts
- podium-gateway/src/test/javascript/e2e/stepdefinitions/util.ts
update tests with correct landing pages
> update e2e tests

- podium-gateway/src/main/java/nl/thehyve/podium/event/StatusUpdateEventListener.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/NotificationService.java
- podium-gateway/src/main/webapp/app/account/settings/settings.component.html
- podium-gateway/src/main/webapp/app/account/settings/settings.component.ts
- podium-gateway/src/main/webapp/app/backoffice/modules/organisation/organisation.component.html
- podium-gateway/src/main/webapp/app/shared/event/podium-event-message.component.ts
- podium-gateway/src/main/webapp/i18n/en/global.json
- Fix displaying message in rejected request
- Email in user profile setting changed to read only
- Add sending email to requester when request is rejected
> Some fixes

- podium-gateway/src/main/webapp/app/backoffice/modules/user-management/user-management-dialog.component.ts
Assigned mandatory lang key when creating new user via admin panel.
> Fix missing lang key when admin creating new user

- podium-gateway/src/main/webapp/app/request/form/request-form.component.html
- podium-gateway/src/main/webapp/app/request/form/request-form.component.ts
- podium-gateway/src/main/webapp/app/request/main-detail/request-main-detail.component.html
- podium-gateway/src/main/webapp/app/request/main-detail/request-main-detail.component.ts
- podium-gateway/src/main/webapp/app/shared/request/action-bars/request-action-toolbar/request-action-toolbar.component.html
- podium-gateway/src/main/webapp/app/shared/request/action-bars/request-action-toolbar/request-action-toolbar.component.ts
- podium-gateway/src/main/webapp/app/shared/request/request-base.ts
Front-end validation to check if attachments have types in non-draft stages
> Validate attachment types in non draft stage

- docs/installation.md
@gijskant we should add this to the main branch right?
> Installation manual

- podium-common/src/main/java/nl/thehyve/podium/common/config/WebConfigurer.java
- podium-common/src/main/java/nl/thehyve/podium/common/web/rest/errors/ExceptionTranslator.java
- podium-gateway/package-lock.json
- podium-gateway/package.json
- podium-gateway/pom.xml
- podium-gateway/src/main/resources/config/bootstrap-prod.yml
- podium-gateway/src/main/resources/templates/error.html
- podium-gateway/yarn.lock
- podium-uaa/src/main/resources/config/bootstrap-prod.yml
- podium-uaa/src/main/resources/config/bootstrap.yml
- pom.xml
- Fix serving of static assets;
- Remove unneeded google page;
- Clean up prod config (force setting a password);
- Update Spring Boot and frontend dependencies.
> Fix for prod environment

- podium-gateway/src/main/java/nl/thehyve/podium/service/DraftService.java
- podium-gateway/src/main/java/nl/thehyve/podium/service/RequestFileService.java
Fixes [PODIUM-284](https://jira.thehyve.nl/browse/PODIUM-284) (submitting a request fails on deleting the draft attachments.)
> Fix deleting of files when deleting a draft.
